# Site settings
title: WhirlyGlobe-Maply
email: contact@mousebirdconsulting.com
description: > # this means to ignore newlines until "baseurl:"
  A high performance map and globe toolkit for iOS and Android.

baseurl: "/WhirlyGlobe"
url: "http://mousebird.github.io/"
twitter_username: mousebirdc
github_username:  mousebird

# Conversion
markdown:    kramdown
highlighter: rouge

gems:
  - jekyll-redirect-from
